remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme
theme: jekyll-theme-dinky
title: Figuring out Github Pages
author: me, @brainy1999
description: Is this working
layout: default
